### PR TITLE
fix infinite wait on failing tests

### PR DESCRIPTION
**Pull request by jsaltermedialab**

### CODE REVIEW

**Comment by jpoles1** [comment]
Hello @jsaltermedialab, thank you for the PR!

Can you please describe the problem you're having and how this commit fixes it in a bit more detail? I've just run the master branch with a failing test and don't seem to be encountering this infinite wait issue.

**Comment by jsaltermedialab** [comment]
Sure.

The problem seems to be [here](https://github.com/jpoles1/gopherbadger/blob/master/main.go#L21) but changing the start to run seems like a more simple fix.

If you use the compiled binary to test another package that has a failing test the output of the test run doesn't match the [regex](https://github.com/jpoles1/gopherbadger/blob/master/main.go#L31) so the float channel returned never receives any input so the program just hangs.

**Comment by jpoles1** [comment]
Just tried again with the compiled binary on a completely separate package, where I intentionally introduced a failng test and I still cannot replicate this issue. Any thoughts @award28?

**Comment by jpoles1** [comment]
Looks like this fix shouldn't cause any problems I just wanna make sure before I merge, thanks for your patience @jsaltermedialab.

**Comment by jsaltermedialab** [comment]
Here is a screenshot of me reproducing it locally including some environment information.

Screen Shot 2020-02-12 at 12 24 53 PM

**Comment by jpoles1** [comment]
Wonder if it's an OS specific issue. Anyway, ran some tests and the changes look good to me. Will go ahead with merge! Thanks again for your contribution @jsaltermedialab.

**Pull request merged**
